// TODO(jawilson): fixme

/*
        {
            id: 'n-',
            romaji: '',
            hiragana: '',
            kanji: '',
            english: '',
        },
        {
            id: 'n-',
            romaji: '',
            hiragana: '',
            kanji: '',
            english: '',
        },
        {
            id: 'n-',
            romaji: '',
            hiragana: '',
            kanji: '',
            english: '',
        },
        {
            id: 'n-',
            romaji: '',
            hiragana: '',
            kanji: '',
            english: '',
        },
        {
            id: 'n-',
            romaji: '',
            hiragana: '',
            kanji: '',
            english: '',
        },

*/


/*
        {
            id: 'v-au',
            romaji: 'au',
            hiragana: "あう",
            kanji: '会う',
            english: 'to meet, to see',
        },
        {
        id: 'v-aku',
        romaji: 'aku',
        hiragana: 'あく',
        kanji: '開く',
        english: 'to open, to become open'
    },
    {
        id: 'v-akeru',
        romaji: 'ake.ru',
        hiragana: 'あける',
        kanji: '開ける',
        english: 'to open',
    },
    {
        id: 'v-ageru',
        romaji: 'age.ru',
        hiragana: 'あげる',
        kanji: '上げる',
        english: 'to give',
    },
    {
        id: 'v-asobu',
        romaji: 'asobu',
        hiragana: 'あそぶ',
        kanji: '遊ぶ',
        english: 'to play, to make a visit',
    },
    {
        id: 'v-abiru',
        romaji: 'abi.ru',
        hiragana: 'あびる',
        kanji: 'あびる',
        english: 'to bathe, to shower',
    },
    {
        id: 'v-arau',
        romaji: 'arau',
        hiragana: 'あらう',
        kanji: '洗う',
        english: 'to wash',
    },
    {
        id: 'v-aru',
        romaji: 'aru',
        hiragana: 'ある',
        kanji: 'ある',
        english: 'to be, to exist, to live, to have',
    },
    {
        id: 'v-aruku',
        romaji: 'aruku',
        hiragana: 'あるく',
        kanji: '歩く',
        english: 'to walk',
    },
    {
        id: 'v-iu',
        romaji: 'iu',
        hiragana: 'いう',
        kanji: '言う',
        english: 'to say, to name, to make a noise',
    },
    {
        id: 'v-iku',
        romaji: 'iku',
        hiragana: 'いく',
        kanji: '行く',
        english: 'to go',
    },
    {
        id: 'v-i.ru',
        romaji: 'i.ru',
        hiragana: 'いる',
        kanji: '居る',
        english: 'to be (animate), to exist (hum)',
    },
    {
        id: 'v-iru',
        romaji: 'iru',
        hiragana: 'いる',
        kanji: '要る',
        english: 'to need',
    },
    {
        id: 'v-ire.ru',
        romaji: 'ire.ru',
        hiragana: 'いれる',
        kanji: '入れる',
        english: 'to put in',
    },
    {
        id: 'v-utau',
        romaji: 'utau',
        hiragana: 'うたう',
        kanji: '歌う',
        english: 'to sing',
    },
    {
        id: 'v-umare.ru',
        romaji: 'umare.ru',
        hiragana: 'うまれる',
        kanji: '生まれる',
        english: 'to be born',
    },
    {
        id: 'v-uru',
        romaji: 'uru',
        hiragana: 'うる',
        kanji: '売る',
        english: 'to sell',
    },
    {
        id: 'v-oki.ru',
        romaji: 'oki.ru',
        hiragana: 'おきる',
        kanji: '起きる',
        english: 'to get up, to rise',
    },
    {
        id: 'v-oku',
        romaji: 'oku',
        hiragana: 'おく',
        kanji: '置く',
        english: 'to put, to place',
    },
    {
        id: 'v-oshie.ru',
        romaji: 'oshieru',
        hiragana: 'おしえる',
        kanji: '教える',
        english: 'to teach, to inform',
    },
    {
        id: 'v-osu',
        romaji: 'osu',
        hiragana: 'おす',
        kanji: '押す',
        english: 'to push, to press',
    },
    {
        id: 'v-oboe.ru',
        romaji: 'oboe.ru',
        hiragana: 'おぼえる',
        kanji: '覚える',
        english: 'to remember, to memorise',
    },
    {
        id: 'v-oyogu',
        romaji: 'oyogu',
        hiragana: 'およぐ',
        kanji: '泳ぐ',
        english: 'to swim',
    },
    {
        id: 'v-ori.ru',
        romaji: 'ori.ru',
        hiragana: 'おりる',
        kanji: '降りる',
        english: 'to get off, to disembark, to dismount',
    },
    {
        id: 'v-owaru',
        romaji: 'owaru',
        hiragana: 'おわる',
        kanji: '終る',
        english: 'to finish, to close',
    },
    {
        id: 'v-kau',
        romaji: 'kau',
        hiragana: 'かう',
        kanji: '買う',
        english: 'to buy',
    },
    {
        id: 'v-kaesu',
        romaji: 'kaesu',
        hiragana: 'かえす',
        kanji: '返す',
        english: 'to return something',
    },
    {
        id: 'v-kaeru',
        romaji: 'kaeru',
        hiragana: 'かえる',
        kanji: '帰る',
        english: 'to go home, to return',
    },
    {
        id: 'v-kakaru',
        romaji: 'kakaru',
        hiragana: 'かかる',
        kanji: 'Kana*',
        english: 'to take (eg time, money)',
    },

*/
    
    ];

/*
    {
        id: '',
        romaji: '',
        hiragana: 'かく',
        kanji: '書く',
        english: 'to write',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'かける',
        kanji: 'Kana*',
        english: 'to put on (eg glasses)',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'かける',
        kanji: 'Kana*',
        english: 'to dial/call (eg phone)',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'かす',
        kanji: '貸す',
        english: 'to lend',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'かぶる',
        kanji: 'Kana*',
        english: 'to wear, to put on (head)',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'かりる',
        kanji: '借りる',
        english: 'to borrow, to have a loan',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'きえる',
        kanji: '消える',
        english: 'to go out, to vanish',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'きく',
        kanji: '聞く',
        english: 'to hear, to listen, to ask',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'きる',
        kanji: '切る',
        english: 'to cut, to chop',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'きる',
        kanji: '着る',
        english: 'to wear, to put on (from shoulders down)',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'くもる',
        kanji: '曇る',
        english: 'to become cloudy, to become dim',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'けす',
        kanji: '消す',
        english: 'to erase, to delete, to turn off power',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'こたえる',
        kanji: '答える',
        english: 'to answer, to reply',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'こまる',
        kanji: '困る',
        english: 'to be worried, to be bothered',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'さす',
        kanji: '差す',
        english: 'to raise (stretch out) hands, to raise (eg umbrella)',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'しまる',
        kanji: '閉まる',
        english: 'to close, to be closed',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'しめる',
        kanji: '閉める',
        english: 'to close, to shut',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'しめる',
        kanji: '締める',
        english: 'to tie, to fasten',
    },
    {
        id: '',
        romaji: '',
        hiragana: 'しる',
        kanji: '知る',
        english: 'to know, to understand',
    },
    ];
*/
